/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MeridianReading {
  'qi' : bigint,
  'vata' : bigint,
  'acidBase' : bigint,
  'meridianName' : string,
  'pitta' : bigint,
  'kapha' : bigint,
}
export interface Patient {
  'id' : bigint,
  'age' : bigint,
  'dob' : string,
  'name' : string,
  'email' : string,
  'gender' : string,
  'notes' : string,
  'phone' : string,
}
export interface Practitioner { 'name' : string, 'role' : string }
export interface Session {
  'id' : bigint,
  'patientId' : bigint,
  'date' : string,
  'meridianReadings' : Array<MeridianReading>,
  'modalities' : Array<string>,
  'notes' : string,
}
export interface _SERVICE {
  'addPatient' : ActorMethod<
    [string, bigint, string, string, string, string, string],
    bigint
  >,
  'addSession' : ActorMethod<
    [bigint, string, Array<string>, Array<MeridianReading>, string],
    bigint
  >,
  'deletePatient' : ActorMethod<[bigint], undefined>,
  'getPatient' : ActorMethod<[bigint], Patient>,
  'getPatients' : ActorMethod<[], Array<Patient>>,
  'getPractitioner' : ActorMethod<[], Practitioner>,
  'getSessions' : ActorMethod<[], Array<Session>>,
  'getSessionsByPatient' : ActorMethod<[bigint], Array<Session>>,
  'setPractitioner' : ActorMethod<[string, string], undefined>,
  'updatePatient' : ActorMethod<
    [bigint, string, bigint, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];