/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MeridianReading = IDL.Record({
  'qi' : IDL.Int,
  'vata' : IDL.Int,
  'acidBase' : IDL.Int,
  'meridianName' : IDL.Text,
  'pitta' : IDL.Int,
  'kapha' : IDL.Int,
});
export const Patient = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'dob' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'gender' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const Practitioner = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const Session = IDL.Record({
  'id' : IDL.Nat,
  'patientId' : IDL.Nat,
  'date' : IDL.Text,
  'meridianReadings' : IDL.Vec(MeridianReading),
  'modalities' : IDL.Vec(IDL.Text),
  'notes' : IDL.Text,
});

export const idlService = IDL.Service({
  'addPatient' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addSession' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(MeridianReading),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deletePatient' : IDL.Func([IDL.Nat], [], []),
  'getPatient' : IDL.Func([IDL.Nat], [Patient], ['query']),
  'getPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
  'getPractitioner' : IDL.Func([], [Practitioner], ['query']),
  'getSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getSessionsByPatient' : IDL.Func([IDL.Nat], [IDL.Vec(Session)], ['query']),
  'setPractitioner' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updatePatient' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MeridianReading = IDL.Record({
    'qi' : IDL.Int,
    'vata' : IDL.Int,
    'acidBase' : IDL.Int,
    'meridianName' : IDL.Text,
    'pitta' : IDL.Int,
    'kapha' : IDL.Int,
  });
  const Patient = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'dob' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'gender' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Practitioner = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Session = IDL.Record({
    'id' : IDL.Nat,
    'patientId' : IDL.Nat,
    'date' : IDL.Text,
    'meridianReadings' : IDL.Vec(MeridianReading),
    'modalities' : IDL.Vec(IDL.Text),
    'notes' : IDL.Text,
  });
  
  return IDL.Service({
    'addPatient' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addSession' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(MeridianReading),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deletePatient' : IDL.Func([IDL.Nat], [], []),
    'getPatient' : IDL.Func([IDL.Nat], [Patient], ['query']),
    'getPatients' : IDL.Func([], [IDL.Vec(Patient)], ['query']),
    'getPractitioner' : IDL.Func([], [Practitioner], ['query']),
    'getSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getSessionsByPatient' : IDL.Func([IDL.Nat], [IDL.Vec(Session)], ['query']),
    'setPractitioner' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updatePatient' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };